### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by 19hours** [rswiftoffice/azure-notificationhubs-flutter#1]
1. Backwards compatibility with pre-1.12 flutter plugins on android
2. Example needs to be updated

**Comment by Anvin-HSS** [comment]
How can I get the token?

**Comment by 19hours** [comment]
Example updated (https://github.com/rswiftoffice/azure-notificationhubs-flutter/commit/67a073c06079cebdc5077c37350c36052664179d)

Todos:
- Subscription of custom tags
- Unsubscription from tags
- Better templates

**Comment by MarkFormigones** [comment]
Hi thank you for your wonderful plugin. I used your plugin and I am waiting for your update regarding custom tags. I hope it will implement this soon.
