### ISSUE TITLE
NullPointerException when using standard template

### ISSUE THREAD

**Issue by Kurokirisu** [rswiftoffice/azure-notificationhubs-flutter#2]
I've noticed that when I use the payload given in the documentation for this package, the notification works fine and shows up on my device if I send a test notification through the Azure portal.

```
{
  "data": {
    "title": "Hello world",
    "body": "to you",
    <!-- extra data payload -->
    ...
  }
}
```

However the standard template that they give is:

`{"data":{"message":"Notification Hub test notification"}}`

If I try to send a notification with this payload I can see in the debug console that the message has been received, but no notification shows up because of a NullPointerException.

```
W/System.err( 2266): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
W/System.err( 2266): 	at com.swiftoffice.azure_notificationhubs_flutter.NotificationService.sendNotification(NotificationService.java:73)
W/System.err( 2266): 	at com.swiftoffice.azure_notificationhubs_flutter.NotificationService.onMessageReceived(NotificationService.java:51)
W/System.err( 2266): 	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:60)
W/System.err( 2266): 	at com.google.firebase.iid.zzg.run(Unknown Source:4)
W/System.err( 2266): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 2266): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 2266): 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
W/System.err( 2266): 	at java.lang.Thread.run(Thread.java:919)
```

I checked the code and this is because the sendNotification is expecting the message to have a title and a body attribute. I plan on fixing this by configuring my backend to only send messages with a title and a body anyway but I thought I'd mention it. iOS doesn't have this problem and shows a single line push notification.

**Comment by Kurokirisu** [comment]
If possible, it would also be great if we could either update our installation or create a new registration with new custom templates.

**Comment by 19hours** [comment]
Custom templates are not a priority right now. I used "title" and "body" for the template format for android similar to iOS. This is temporary and may change in the future when we have custom templates. For now, if you don't need a title, you can just pass in a blank string.

https://github.com/rswiftoffice/azure-notificationhubs-flutter/blob/f2e14f2ca985a91bb716f6fa0c0f47f0d9df8383/android/src/main/java/com/swiftoffice/azure_notificationhubs_flutter/NotificationService.java#L73
