### ISSUE TITLE
notificationhubs example showing NoSuchMethodError.

### ISSUE THREAD

**Issue by Aashikms** [rswiftoffice/azure-notificationhubs-flutter#3]
I am trying to connect flutter application with Azure notification hub. I tried the example project given in the repository. I followed all instruction to setup the application as per readme.
When i compiled and ran the application i am receiving below error/warning.
~~~
I/flutter (16570): The following NoSuchMethodError was thrown attaching to the render tree:
I/flutter (16570): The method 'configure' was called on null.
I/flutter (16570): Receiver: null
I/flutter (16570): Tried calling: configure(onLaunch: Closure: (Map<String, dynamic>) => Future<Null>, onMessage:
I/flutter (16570): Closure: (Map<String, dynamic>) => Future<Null>, onResume: Closure: (Map<String, dynamic>) =>
I/flutter (16570): Future<Null>, onToken: Closure: (String) => Future<Null>)
~~~
![image](https://user-images.githubusercontent.com/31242566/81158274-6f6cd280-8fa5-11ea-8a81-970cceb7d541.png)

**Comment by 19hours** [comment]
Initialise anh: _anh = AzureNotificationhubsFlutter();

**Comment by Aashikms** [comment]
Oh how silly of me. Thanks.
