### ISSUE TITLE
These errors occur when run

### ISSUE THREAD

**Issue by sxs1995** [rswiftoffice/azure-notificationhubs-flutter#4]
![image](https://user-images.githubusercontent.com/22333956/81185671-749d4200-8fe4-11ea-9334-24d8f0f63c31.png)

**Comment by michaelmairegger** [comment]
I have the same error

**Comment by michaelmairegger** [comment]
I have fixed this issue by adding the maven repository to build.gradle

```
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://dl.bintray.com/microsoftazuremobile/SDK"
        }
    }
}
```

**Comment by 19hours** [comment]
Try re-syncing your project in android studio

> I have fixed this issue by adding the maven repository to build.gradle
> 
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         maven {
>             url "https://dl.bintray.com/microsoftazuremobile/SDK"
>         }
>     }
> }
> ```

It's already declared here

https://github.com/rswiftoffice/azure-notificationhubs-flutter/blob/67a073c06079cebdc5077c37350c36052664179d/android/build.gradle#L49

**Comment by michaelmairegger** [comment]
@19hours without this repository information the build will not succeed

**Comment by sxs1995** [comment]
@19hours I have a new issue, please help me if possible, thanks.
![image](https://user-images.githubusercontent.com/22333956/81390259-b7c6f480-914d-11ea-9244-38de3b0ab0c9.png)

**Comment by 19hours** [comment]
Clean project, invalidate your caches and run again
